### ISSUE TITLE
there is a problem between in fbank_feature.shape and pitch_feature.shape.

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#102]
1.fbank_feature:
from kaldi.feat.wave import WaveData
from kaldi.base._iostream import *
from kaldi.util.io import *
wavedata=WaveData()
inp=Input("BAC009S0912W0121.wav")
wavedata.read(inp.stream())
s3=wavedata.data()
s3 = s3[:,::int(wavedata.samp_freq / sf_fbank)]
m3 = SubVector(mean(s3, axis=0))
f3=fbank.compute_features(m3,sf_fbank,1.00)
print f3.shape 

resutl:(_394_,80)

2.picth_feature
from kaldi.feat.mfcc import Mfcc, MfccOptions
from kaldi.feat.pitch import PitchExtractionOptions,ProcessPitchOptions
from kaldi.feat.pitch import *
pitch_opts = PitchExtractionOptions()
pitch_opts.samp_freq=16000.0
feat_pitch=compute_kaldi_pitch(pitch_opts,m3)
processpitchoptions=ProcessPitchOptions()
f_pitch=process_pitch(processpitchoptions,feat_pitch)
print f_pitch.shape

result:  (_395_,3)

why is the first dimension different?

**Comment by liuchenbaidu** [comment]
if i chang pitch_opts.samp_frep=16000.0 to pitch_opts.resample_freq=16000.0 then it's ok.

**Comment by dogancan** [comment]
This is because of the way Kaldi feature extraction works -- not really a PyKaldi issue. 

By default, Kaldi downsamples input signal to 4KHz before pitch extraction -- this is the default value of PitchExtractionOptions.resample_freq. Depending on how many samples are available within the audio signal, feature extraction might produce one additional feature frame due to rounding effects. 
It is perfectly fine to drop the last pitch feature frame when appending pitch features to fbank features or any other features.
