### ISSUE TITLE
How to turn off KALDI_LOG

### ISSUE THREAD

**Issue by bobzsj87** [pykaldi/pykaldi#112]
I keep getting kaldi logs such as "LOG ([5.5.196~1-5dc5d]:~CachingOptimizingCompiler():nnet-optimize.cc:710) 0.00592 seconds taken in nnet3 compilation total (breakdown: 0.00402 compilation, 0.00111 optimization, 0 shortcut expansion, 0.000317 checking, 1.91e-05 computing indexes, 0.00046 misc.) + 0 I/O." from my application. Is there anyway to turn that off?

**Comment by vrmpx** [comment]
Kaldi does not support disabling logs but you can redirect them to a log file or /dev/null since all logs are printed to stderr. 

Here is a simple example, using one of the example scripts. Running copy matrix to read a matrix and print it to the command line: 
```
root@4fdd8743fa6b:/pykaldi/examples/kaldi-style-executables/copy-matrix# python copy-matrix.py ark,t:mat.txt ark,t:-
copy-matrix.py ark,t:mat.txt ark,t:-
1  [
  0 1 2 3 4
  5 6 7 8 9 ]
```
As you can see there is an additional line logging the command we just ran (i.e., `copy-matrix.py ark,t:mat.txt ark,t:-`) by forwarding to stderr to /dev/null, as follows:
```
root@4fdd8743fa6b:/pykaldi/examples/kaldi-style-executables/copy-matrix# python copy-matrix.py ark,t:mat.txt ark,t:- 2>/dev/null
1  [
  0 1 2 3 4
  5 6 7 8 9 ]
```

**Comment by vrmpx** [comment]
I am closing this issue but feel free to re-open if you have any further questions.
