### ISSUE TITLE
test seems essential for proper install

### ISSUE THREAD

**Issue by davidavdav** [pykaldi/pykaldi#122]
I've now successfully installed pykaldi in a virtual environment on both linux and macos, but in both cases I noticed that 
```
python setup.py test
```
is necessary before `kaldi` can be imported in python, apparently the test installs some things that `python setup.py install` missed.  

Following the readme leads to a correct installation, but I wonder of these installs that `test` carries out should not be moved to `install`.

**Comment by vrmpx** [comment]
Are you trying to import things from within pykaldi repo after installation is complete?

If thats the case, then you'll end up importing the local python modules inside pykaldi/kaldi which do not work since .so files are not installed in there.

So when you run the tests, .so files are copied into pykaldi/kaldi folder, just like in the case of running `python setup.py develop`, and imports from pykaldi directory start working.

**Comment by davidavdav** [comment]
Yes, this is a correct assessment of the situation
