### ISSUE TITLE
some imports appear to be really really slow

### ISSUE THREAD

**Issue by davidavdav** [pykaldi/pykaldi#127]
Hello, 

I found that some imports take quite a while, at least on my Mac laptop.  Specifically
```python
from kaldi.asr import NnetLatticeFasterOnlineRecognizer
```
takes over 7 seconds.  Is this just dynamically linking the relevant .so (on on mac .dylib) files?  

On my system `libkaldi-nnet3.dylib` is 17MB, which appears the largest of all the .dylib files, but still this is not a lot to load from disc (maybe the linking takes long?).

**Comment by vrmpx** [comment]
There doesn't seem to be much room to work with here since the asr module pretty much imports all pykaldi modules. Seems like the slowness comes from the python code being interpreted and not the linking itself (although it might contribute a bit). 

Speeding up this import would require splitting up most large modules inside pykaldi so we can import things separately, but that would not be very nice in terms of user experience.

**Comment by davidavdav** [comment]
OK, thanks.  Is it a lot of python code that gets generated by clif? I had the impression it was all precompiled, so there probably is not much leeway there. 

BTW on a supposedly beefier linux machine the import mentioned above takes about a second, so perhaps it is related to MacOS or the laptopness.  Usually I don't see such large speed differences.
