### ISSUE TITLE
Install error from source

### ISSUE THREAD

**Issue by Winderxia** [pykaldi/pykaldi#128]
Hello,

I have a problem by install pykaldi, during install there are no error, but at the step: python setup.py install, getting errors , I have tried many times but it always so, I want to ask if you know what can cause this problem and how can I fix it?Thank you

Line .123456789.123456789.123456789.123456789
1:\n
2:from "itf/decodable-itf.h":\n
3:	namespace `kaldi`:\n
4:		class DecodableInterface:\n
5:			"""Decodable interface definition."""\n
6:\n
............

_ParseError: invalid statement in indented block (at char 86), (line:5,col:7)

............

**Comment by vrmpx** [comment]
Seems like a problem with your clif installation. By any chance, did you install it from the original source instead of [our fork](https://github.com/pykaldi/clif)? Also make sure that or you are working with the pykaldi branch instead of the master branch. All this is taken care of by the clif install script.
