### ISSUE TITLE
Can I use pykaldi to convert a wav file to text using a model I already created and trained in Kaldi?

### ISSUE THREAD

**Issue by zachadasm16** [pykaldi/pykaldi#134]
Was just wondering if these tools are available in the tool set before I continue to use it

**Comment by zachadasm16** [comment]
If I can do this what are the best tools to look at?

**Comment by zachadasm16** [comment]
also is there a way to do this with converting the .wav into a numpy array

**Comment by PhantomGrin** [comment]
Hi @zachadasm16 
Since you are one step ahead me and I have no way to contact you other than here, I 'll leave a message here. Sorry for the distraction.

Can I know whether you run tests on your Kaldi model to convert wave to transcribe (using terminal)? and if you did, How did you do it? I made the HCLG.fst. I am stuck as to what to do next.

**Comment by vrmpx** [comment]
Hi @zachadasm16 ,
You should take a look at https://github.com/pykaldi/pykaldi/tree/master/examples/setups/aspire, and try to replicate this setup with your own models.
