### ISSUE TITLE
how can I get mfcc or plp feature from .wav file?

### ISSUE THREAD

**Issue by stepholi** [pykaldi/pykaldi#145]

**Comment by vrmpx** [comment]
Hello,
Pykaldi has different ways of computing these features. How do plan on using them? (it would be great if you could provide some code example). 

Take a look at the [MFCC extraction example](https://github.com/pykaldi/pykaldi/blob/master/examples/notebooks/mfcc-extraction.ipynb), or search for [MFCC in the docs](https://pykaldi.github.io/search.html?q=mfcc&check_keywords=yes&area=default).

**Comment by pawel-rozwoda** [comment]
I guess it is better to continue this issue rather than opening a new one.
Example mentioned by @vrmpx works. However I do not know how to apply parameters such as window size and shift for plp method. 
There is nothing in docs about that:    https://pykaldi.github.io/api/kaldi.feat.html#module-kaldi.feat.plp
