### ISSUE TITLE
Clif build fails on Ubuntu 18.04 Python 3.8

### ISSUE THREAD

**Issue by Alienmaster** [pykaldi/pykaldi#234]
Hi,
i tried to build cliff on Ubuntu 18.04 LTS with Python 3.8 and get the following error:

`[1787/1788]` Building CXX object tools/clif/pyt...if_python_utils_proto_util.dir/proto_util.cc.o
FAILED: tools/clif/python/utils/CMakeFiles/clif_python_utils_proto_util.dir/proto_util.cc.o
/usr/bin/c++  -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dclif_python_utils_proto_util_EXPORTS -Itools/clif/python/utils -I/home/alienmaster/projects/pykaldi/tools/clif_backend/llvm/tools/clif/python/utils -Iinclude -I/home/alienmaster/projects/pykaldi/tools/clif_backend/llvm/include -I/home/alienmaster/projects/pykaldi/tools/protobuf/include -I/home/alienmaster/projects/pykaldi/tools/clif_backend/llvm/tools -Itools -I/home/alienmaster/projects/kaldi-model-server/pykaldi_env/include/python3.8 -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG -fPIC -MD -MT tools/clif/python/utils/CMakeFiles/clif_python_utils_proto_util.dir/proto_util.cc.o -MF tools/clif/python/utils/CMakeFiles/clif_python_utils_proto_util.dir/proto_util.cc.o.d -o tools/clif/python/utils/CMakeFiles/clif_python_utils_proto_util.dir/proto_util.cc.o -c tools/clif/python/utils/proto_util.cc
tools/clif/python/utils/proto_util.cc:176:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
tools/clif/python/utils/proto_util.cc:356:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
tools/clif/python/utils/proto_util.cc:546:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
tools/clif/python/utils/proto_util.cc:897:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
ninja: build stopped: subcommand failed.
`

Like in Issue #232 i tried several combinations of Ubuntu and Python. Ubuntu 20.04 never succeeded. Ubuntu 18.04 with python 3.6 and 3.7 works fine but 3.8 doesnt work.

If needed i can send more detailed informations.

**Comment by tangemicioglu** [comment]
I think this may be related to protobuf, and apparently they made the change to fix the issue [in a recent commit](https://github.com/protocolbuffers/protobuf/commit/c2c13a558ab1473b9b8ea60f9b550f96a2d1a577) but it's not in any release version yet.

**Comment by Alienmaster** [comment]
Its in the 3.15 release changed :)

**Comment by bmilde** [comment]
@tangemicioglu thanks for the protobuf hint! This wasn't the problem, as the protobuf version that pykaldi uses seems to have 0s everywhere in the struct instead of nullptr. However this file in clif_backend: ./clif_backend/build_matcher/tools/clif/python/utils/proto_util.cc

contained a Python wrapped struct that looks similar in line 176:

PyTypeObject wrapper_Type = {
  PyVarObject_HEAD_INIT(&PyType_Type, 0)
  "clif.python.utils.proto_util.ProtoTypeInfo", // tp_name
  sizeof(wrapper),                     // tp_basicsize
  0,                                   // tp_itemsize
  _dtor,                               // tp_dealloc
  nullptr,                             // tp_print
  nullptr,                             // tp_getattr
  nullptr,                             // tp_setattr
  nullptr,                             // tp_compare
  nullptr,                             // tp_repr
  nullptr,                             // tp_as_number
  nullptr,                             // tp_as_sequence
  nullptr,                             // tp_as_mapping
  nullptr,                             // tp_hash
  nullptr,                             // tp_call
  nullptr,                             // tp_str
  nullptr,                             // tp_getattro
  nullptr,                             // tp_setattro
  nullptr,                             // tp_as_buffer
  Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE, // tp_flags
  "CLIF wrapper for ::clif_proto::ProtoTypeInfo", // tp_doc
  nullptr,                             // tp_traverse
  nullptr,                             // tp_clear
  nullptr,                             // tp_richcompare
  0,                                   // tp_weaklistoffset
  nullptr,                             // tp_iter
  nullptr,                             // tp_iternext
  nullptr,                             // tp_methods
  nullptr,                             // tp_members
  Properties,                          // tp_getset
  nullptr,                             // tp_base
  nullptr,                             // tp_dict
  nullptr,                             // tp_descr_get
  nullptr,                             // tp_descr_set
  0,                                   // tp_dictoffset
  _ctor,                               // tp_init
  _new,                                // tp_alloc
  PyType_GenericNew,                   // tp_new
  _del,                                // tp_free
  nullptr,                             // tp_is_gc
  nullptr,                             // tp_bases
  nullptr,                             // tp_mro
  nullptr,                             // tp_cache
  nullptr,                             // tp_subclasses
  nullptr,                             // tp_weaklist
  nullptr,                             // tp_del
  0,                                   // tp_version_tag
};


Changing the tp_print line from nullptr to 0, with similar occurrences in line 356, 546, 897 as hinted in the error message solved the issue. A successive call to ./install_clif.sh then succesfully compiles proto_util.cc. The fix is easy, but isn't ./clif_backend/build_matcher/tools/clif/python/utils/proto_util.cc an auto-generated file?

**Comment by bmilde** [comment]
After that, all tools/prerequistes did complie succefully, however pykaldi didn't and a similar error occured (when running "python3 setup.py install" in pykaldis root):

[40/983] Building CXX object kaldi/cudamatrix/CMakeFiles/_cu_matrixdim.dir/cu-matrixdim-clifwrap.cc.o
FAILED: kaldi/cudamatrix/CMakeFiles/_cu_matrixdim.dir/cu-matrixdim-clifwrap.cc.o 
/usr/bin/c++  -D_cu_matrixdim_EXPORTS -I../kaldi/lib -I../kaldi -Ikaldi -I../tools/kaldi/src -I/usr/include/python3.8 -I/home/me/projects/kaldi-model-server_new/pykaldi_env/lib/python3.8/site-packages/numpy/core/include -std=c++11 -I.. -isystem /home/me/projects/pykaldi_3.8/tools/kaldi/tools/openfst/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/me/projects/pykaldi_3.8/tools/kaldi/tools/ATLAS_headers/include -msse -msse2 -pthread -g -fPIC -Wno-maybe-uninitialized -fPIC -MD -MT kaldi/cudamatrix/CMakeFiles/_cu_matrixdim.dir/cu-matrixdim-clifwrap.cc.o -MF kaldi/cudamatrix/CMakeFiles/_cu_matrixdim.dir/cu-matrixdim-clifwrap.cc.o.d -o kaldi/cudamatrix/CMakeFiles/_cu_matrixdim.dir/cu-matrixdim-clifwrap.cc.o -c kaldi/cudamatrix/cu-matrixdim-clifwrap.cc
kaldi/cudamatrix/cu-matrixdim-clifwrap.cc:151:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
kaldi/cudamatrix/cu-matrixdim-clifwrap.cc:325:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
kaldi/cudamatrix/cu-matrixdim-clifwrap.cc:499:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
kaldi/cudamatrix/cu-matrixdim-clifwrap.cc:673:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
kaldi/cudamatrix/cu-matrixdim-clifwrap.cc:828:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };

The tp_print nullptr seems to be in lots of other files as well, so its not enough to just change this occurence:

build/kaldi/itf/decodable-itf-clifwrap.cc:190:  nullptr,                             // tp_print
build/kaldi/itf/options-itf-clifwrap.cc:319:  nullptr,                             // tp_print
build/kaldi/itf/context-dep-itf-clifwrap.cc:312:  nullptr,                             // tp_print
build/kaldi/fstext/symbol-table-clifwrap.cc:148:  nullptr,                             // tp_print
build/kaldi/fstext/symbol-table-clifwrap.cc:1023:  nullptr,                             // tp_print
build/kaldi/fstext/symbol-table-clifwrap.cc:1315:  nullptr,                             // tp_print
build/kaldi/fstext/determinize-lattice-clifwrap.cc:109:  nullptr,                             // tp_print
build/kaldi/chain/chain-datastruct-clifwrap.cc:109:  nullptr,                             // tp_print
build/kaldi/base/fstream-clifwrap.cc:119:  nullptr,                             // tp_print
build/kaldi/base/fstream-clifwrap.cc:303:  nullptr,                             // tp_print
build/kaldi/base/sstream-clifwrap.cc:173:  nullptr,                             // tp_print
build/kaldi/base/sstream-clifwrap.cc:411:  nullptr,                             // tp_print
build/kaldi/base/sstream-clifwrap.cc:665:  nullptr,                             // tp_print
build/kaldi/base/timer-clifwrap.cc:142:  nullptr,                             // tp_print
build/kaldi/base/iostream-clifwrap.cc:98:  nullptr,                             // tp_print
build/kaldi/base/iostream-clifwrap.cc:253:  nullptr,                             // tp_print
build/kaldi/base/iostream-clifwrap.cc:397:  nullptr,                             // tp_print
build/kaldi/base/kaldi-math-clifwrap.cc:71:  nullptr,                             // tp_print
kaldi/matrix/matrix-ext.cc:145:  nullptr,                             // tp_print
kaldi/matrix/matrix-ext.cc:369:  nullptr,                             // tp_print
kaldi/matrix/matrix-ext.cc:578:  nullptr,                             // tp_print
kaldi/matrix/matrix-ext.cc:802:  nullptr,                             // tp_print

 ^
[41/983] Building CXX object kaldi/fstext/CMakeFiles/properties.dir/properties-clifwrap.cc.o

However every occurence of this can be automatically replaced with:

     find ./ -type f -exec sed -i 's#nullptr,                             // tp_print#0,                             // tp_print#g' {} \;

Unfortunatly when I rerun the files are regenerated  and this error reoccues. So it would probably be better to tackle the root of this issue.

**Comment by bmilde** [comment]
I tried to follow how CLIF generated the nullptr in ./clif_backend/build_matcher/tools/clif/python/utils/proto_util.cc

So basically the header said:

    //////////////////////////////////////////////////////////////////////
    // This file was automatically generated by CLIF to run under Python 3
    // Version 0.3
    //////////////////////////////////////////////////////////////////////
    // source: /home/me/projects/pykaldi_3.8/tools/clif_backend/llvm/tools/clif/python/utils/proto_util.clif

    from from "clif/python/proto_util.h":

and thats basically including

    ./protobuf/include/google/protobuf/descriptor.h

But I can't see how that generates nullptr since I replace all tp_prints in the whole source dir (and there were non in protobuf to begin with)

**Comment by bmilde** [comment]
Unfortunately I couldn't tackle the root issue, but I managed to compile everything by replacing /usr/bin/c++ with:

    #!/bin/bash
    sed -i 's#nullptr,                             // tp_print#0,                             // tp_print#g' ${@: -1}
    g++ "$@"

This basically replaces every occurrence of this nullptr tp_print with 0 for the file in the last argument and then calls gcc with the original arguments. I'm not a big fan of cmake/ninja, so I wasn't sure how to do it there. But /usr/bin/c++ is what ninja called to compile cc files.

**Comment by bmilde** [comment]
Dogan suggested a fix for tp_print, my silly workaround isn't needed anymore.
