### ISSUE TITLE
Explanation about releases

### ISSUE THREAD

**Issue by mauvilsa** [pykaldi/pykaldi#237]
In this git repository there are no tags which means that github shows no releases. But apparently there have been releases. In conda (https://anaconda.org/Pykaldi/pykaldi-cpu) there was at some point version 0.0.9 which is no longer there. Now you can see files for versions 0.1.0 and 0.1.3. It seems that versions 0.1.1 and 0.1.2 were skipped. Though, more weirdly in the master branch the file `https://github.com/pykaldi/pykaldi/blob/master/kaldi/__version__.py` says 0.1.2. Where did version 0.1.3 come from? On the other hand, in docker hub there seems to be an image, but no appropriate tags (https://hub.docker.com/r/pykaldi/pykaldi/tags) to know to which version it corresponds.

It would be great if the release process is explained in the readme and that there are git tags for each of the releases and appropriate tags in docker hub. Is it likely that this can be done?

It also seems that this project is not very active currently. If this is because the original maintainers are not investing time on it anymore, it would be good if you try to find people and give appropriate permissions in order to help maintain it. This obviously includes an improved release process.

@dogancan @vrmpx

**Comment by mauvilsa** [comment]
@dogancan @vrmpx would be good to get some input here, even if it is a short one.

**Comment by tjysdsg** [comment]
Also, it would be really nice if anyone can update the pykaldi [anaconda package](https://anaconda.org/pykaldi/pykaldi) to the latest package

**Comment by mauvilsa** [comment]
Great to see some activity here. Maybe @bmilde @milde can comment about this.

**Comment by bmilde** [comment]
I'm not sure about anything pre 0.1.x, but generally we upgrade the last version number for small changes and 0.x for larger changes involving for example Kaldi upgrades. 

We recently upgrade the Kaldi version from an 2018 one to a version from 2021, due to that we now have PyKaldi 0.2.x. We'll probably soon upgrade protobuf and clif to more recent versions as well, when we do that we will probably have PyKaldi 0.3.x.

Note that you need matching patched Kaldi versions from https://github.com/pykaldi/kaldi/tree/pykaldi_01 for PyKaldi 0.1.x. and https://github.com/pykaldi/kaldi/tree/pykaldi_02 for 0.2.x. install_kaldi.sh will pull the correct version for the current git version of PyKaldi.

We'll soon have more official releases with pip wheels as well.

**Comment by mauvilsa** [comment]
@bmilde Thank you for the response. Though note that my original question was mostly concerned about tags which you have not mentioned. Ideally for each release in pypi there should be a corresponding tag here in github. And the tag should be for the exact commit that was used to create the package. Just changing a version file is not enough. The tags help out considerably and github would list them under releases.

There are tools that help in doing this and several strategies. Could be that somehow a release is triggered which also pushes to github the new tag for it. Or could be the other way around, that when a tag is pushed then the release process is triggered. I use the latter in several open source projects with the help of bump2version. An example configuration is https://github.com/omni-us/jsonargparse/blob/master/.bumpversion.cfg. It is very convenient because with a single command the version file(s) is(are) updated and a commit with a good description is created and tagged appropriately. Would be good to see something like this in pykaldi. If bump2version seems interesting to you I would be happy to help in implementing it. Let me know your thoughts.
