### ISSUE TITLE
GPU Multithread/Multiprocess Decoding

### ISSUE THREAD

**Issue by uday156** [pykaldi/pykaldi#239]
Hey there, Has anyone tried Multi-thread or Multiprocessing in GPU with the Pykaldi Aspire model.
Can someone guide me through the process, thank you.

**Comment by bmilde** [comment]
We have multi threaded decoding in this project: https://github.com/uhh-lt/kaldi-model-server

Note that due to GIL in Python you can only use threads in Python for I/O, so in our case we use it to compute decoding while waiting for a microphone buffer to fill to get the best latency in online decoding.

You can probably also use a threaded decoder class in offline decoding, then you'd have threads in Kaldi. I've never tried that.

As for GPU decoding, there seems to be a cudadecoder in the most recent versions of Kaldi, but there isn't support for it in PyKaldi yet.
