### ISSUE TITLE
ImportError: undefined symbol

### ISSUE THREAD

**Issue by quents** [pykaldi/pykaldi#243]
I have already a Kaldi installation on my Linux system. I also installed pykaldi using conda:

`conda install -c pykaldi pykaldi`

When I try to import from kaldi.decoder import LatticeFasterDecoderOptions, I got the following error:

`ImportError: /kaldi/src/lib/libkaldi-matrix.so: undefined symbol: _ZNK5kaldi13MessageLogger10LogMessageEv`

At some imports I also get the same error with libkaldi-tree.so

I have no problems with Kaldi, the training and decoding processes run smoothly.

Can you help? Thanks.

**Comment by bmilde** [comment]
You can't just use any Kaldi version with PyKaldi, you need a patched version of Kaldi matching your PyKaldi version. The reason is that we need some changes to get CLIF to play nice with Kaldi.

For PyKaldi 0.1.x you need:  https://github.com/pykaldi/kaldi/tree/pykaldi_01

For PyKaldi 0.2.x you need:  https://github.com/pykaldi/kaldi/tree/pykaldi_02

See https://github.com/pykaldi/pykaldi/blob/master/tools/install_kaldi.sh as well.

Right now i recommend building from scratch to get PyKaldi 0.2, but we'll host pip wheels very soon for the new version as well. The Conda package might be outdated.
