### ISSUE TITLE
gpu is available, but pykaldi cannot use it

### ISSUE THREAD

**Issue by fanzfeng** [pykaldi/pykaldi#247]
1. Ubuntu 16.04.6 LTS
2. install pykaldi by `conda install -c pykaldi pykaldi`
3. detail
```
(pykaldi) root@c80918aff80f:/share/kaldi/src# python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kaldi.cudamatrix import cuda_available
>>> cuda_available()
False
>>> from pynvml import *
>>> nvmlInit()
>>> nvmlSystemGetDriverVersion()
b'418.87.00'
>>> nvmlDeviceGetCount()
8
```

**Comment by bmilde** [comment]
You're probably on the old Kaldi version and GPU supported is limited there, since not all CUDA versions will work and the old Kaldi version couldn't build for all sm CUDA archs. If you want to use the GPU functions I recommend compiling from scratch with a new Ubuntu version and newish CUDA with an up-to-date git version of pykaldi. You will need to edit install_kaldi.sh and set cuda=yes, as the default build is for CPU. Most users do inference with pykaldi and use plain kaldi to train the models, that is why we default to CPU builds.
