### ISSUE TITLE
svn: E170013: Unable to connect to a repository at URL 'https://llvm.org/svn/llvm-project/llvm/trunk'

### ISSUE THREAD

**Issue by hontarenkoYana** [pykaldi/pykaldi#248]
Hello!

Can anybody help me with this issue?
I tried to follow instruction of building from source and have error when run `./install_clif.sh`.
```
Destination <path to pykaldi folder>/tools/clif already exists.
Already up to date.
<my venv path>/bin/ninja
Using ninja for the clif backend build.
svn: E170013: Unable to connect to a repository at URL 'https://llvm.org/svn/llvm-project/llvm/trunk'
svn: E175009: The XML response contains invalid XML
svn: E130003: Malformed XML: no element found
```
All dependencies before was installed correctly. Also, If I open link https://llvm.org/svn/llvm-project/llvm/trunk I got 404 Not Found. Does link changed?

**Comment by quents** [comment]
I guess the problem exists because the llvm link is down. Does anyone know the exact github version of trunk@307315?

**Comment by XavierGithub** [comment]
You can clone from https://github.com/bobzsj87/llvm-307315

**Comment by quents** [comment]
Thank you, @XavierGithub, I have also edited the install_clif.sh

Instead of, 
`#svn co https://llvm.org/svn/llvm-project/llvm/trunk@307315 llvm
#cd llvm/tools
#svn co https://llvm.org/svn/llvm-project/cfe/trunk@307315 clang`

just past this:
```
wget https://github.com/llvm/llvm-project/archive/llvmorg-5.0.0-rc1.tar.gz
tar -xvf llvmorg-5.0.0-rc1.tar.gz
cp -r llvm-project-llvmorg-5.0.0-rc1/llvm/ .
cp -r llvm-project-llvmorg-5.0.0-rc1/clang llvm/tools/
cd llvm/tools
```
I couldn't find the version 307315 but I found 309*** from the official github repo: https://github.com/llvm/llvm-project/releases/tag/llvmorg-5.0.0-rc1

**Comment by hontarenkoYana** [comment]
@quents,  it worked!
After replacing part of the code which you described everything installed correctly. 
Thank you for help!
