### ISSUE TITLE
How to use pykaldi to caculate phone posterior？

### ISSUE THREAD

**Issue by red-fly** [pykaldi/pykaldi#273]
I want to calculate GOP by pykaldi ，and now I need phone-alignment and phone posterior ，I can get the former by aligner，however I don‘t know how to get the latter.

**Comment by tjysdsg** [comment]
I implemented GOP using pykaldi a while ago, I can share the posterior calculation code:

```python
import cython
from kaldi.nnet3 import (Nnet, NnetSimpleComputationOptions, set_batchnorm_test_mode,
                         set_dropout_test_mode, collapse_model,
                         CollapseModelConfig, CachingOptimizingCompiler,
                         DecodableNnetSimple)
from kaldi.matrix import Matrix, Vector
import numpy as np
cimport numpy as np

ctypedef np.float_t float_t

@cython.boundscheck(False)
@cython.wraparound(False)
cpdef np.ndarray[float_t, ndim=2] nnet3_compute(nnet: Nnet, np.ndarray[float_t, ndim=2] _features,
                                               float_t[:, :] _online_ivectors = None,
                                               int online_ivector_period = 0):
    cdef features = Matrix(_features)
    cdef opts = NnetSimpleComputationOptions()
    opts.frames_per_chunk = 50
    opts.extra_left_context = 0
    opts.extra_right_context = 0
    opts.extra_left_context_initial = -1
    opts.extra_right_context_final = -1
    opts.acoustic_scale = 1.0

    set_batchnorm_test_mode(True, nnet)
    set_dropout_test_mode(True, nnet)
    collapse_model(CollapseModelConfig(), nnet)
    cdef compiler = CachingOptimizingCompiler(nnet, opts.compiler_config)
    if _online_ivectors is not None:
        online_ivectors = Matrix(_online_ivectors)
        nnet_computer = DecodableNnetSimple(opts, nnet, Vector(), features, compiler, None, online_ivectors,
                                        online_ivector_period)
    else:
        nnet_computer = DecodableNnetSimple(opts, nnet, Vector(), features, compiler, None)
    cdef int n_frames = nnet_computer.num_frames()
    cdef ret = Matrix(n_frames, nnet_computer.output_dim())
    cdef int i
    for i in range(n_frames):
        row = ret.row(i)
        nnet_computer.get_output_for_frame(i, row)
    return ret.numpy().astype(np.float)
```

It's in Cython, but the main API calls are pretty clear

**Comment by tjysdsg** [comment]
BTW, (if i remember correctly) I translated this from kaldi C++ source code

**Comment by ryanxiauic** [comment]
> BTW, (if i remember correctly) I translated this from kaldi C++ source code

Sorry to interrupt. I am working on a GOP project. The way i calaulate gop is just the same as your code, but it seems the result gop isn't the largest almost all phones. The posteriors on some phones is  always the largest, because its posterior mapping from pdf have been added most times. For example, phone 4 has been added 3376 times. I was wondering if the posterior can be simply just be added or am I misunderstand something. Could you please check if the problem also reveal in your case ?

I am very forward to have further communication with you. Hope for your reply~

**Comment by tjysdsg** [comment]
If I understand your problem correctly, you mean that when calculating the posteriors of some phones, some pdfs were summed for thousands of times. Therefore, some phone posteriors are very large, and the GOP result is unusable.

If that's the case, then I suspect that there may be an error when constructing the pdf2phone mapping. This is just my guess because I haven't encountered such an issue before.

Since I basically copied the implementation from [(an older version of) here](https://github.com/kaldi-asr/kaldi/blob/master/src/bin/compute-gop.cc), maybe you can find more information by looking at it.

**Comment by tjysdsg** [comment]
In addition, I just found an old [PR]((https://github.com/kaldi-asr/kaldi/pull/3526/files#diff-25825feb9e9549013caa6c8bec60a09b1f571dad690da146654d01e34befd863R105)) from danpovey for calculating posteriors using pdfs. So yes, the posteriors can be simply be added to get phone posteriors

**Comment by ryanxiauic** [comment]
> > > BTW, (if i remember correctly) I translated this from kaldi C++ source code
> > 
> > 
> > Sorry to interrupt. I am working on a GOP project. The way i calaulate gop is just the same as your code, but it seems the result gop isn't the largest almost all phones. The posteriors on some phones is always the largest, because its posterior mapping from pdf have been added most times. For example, phone 4 has been added 3376 times. I was wondering if the posterior can be simply just be added or am I misunderstand something. Could you please check if the problem also reveal in your case ?
> > I am very forward to have further communication with you. Hope for your reply~
> 
> If I understand your problem correctly, you mean that when calculating the posteriors of some phones, some pdfs were summed for thousands of times. Therefore, some phone posteriors are very large, and the GOP result is unusable.
> 
> If that's the case, then I suspect that there may be an error when constructing the pdf2phone mapping. This is just my guess because I haven't encountered such an issue before.
> 
> Since I basically copied the implementation from [(an older version of) here](https://github.com/kaldi-asr/kaldi/blob/master/src/bin/compute-gop.cc), maybe you can find more information by looking at it.

Thank you for your help. I've found a configuration error with the aligner frame_subsampling_factor. I set it to 3. Therefore, it doesn't consistent with frame number. Now, everything works well.
