### ISSUE TITLE
installation fail

### ISSUE THREAD

**Issue by fgvbrt** [pykaldi/pykaldi#35]
Hi, I can not install pykaldi.

when running python setup.py install I get error

Using PYCLIF: /home/mpavlov/anaconda/envs/test/bin/pyclif
Using CLIF_MATCHER: /home/mpavlov/anaconda/envs/test/clang/bin/clif-matcher
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mpavlov/voice/pykaldi/build
ninja: error: '/home/mpavlov/anaconda/envs/kaldi/lib/libpython3.5m.so', needed by 'lib/kaldi/_clif.so', missing and no known rule to make it
Command '['ninja']' returned non-zero exit status 1

**Comment by vrmpx** [comment]
Hi @fgvbrt, 
It appears to be a miss-match between the conda environments of pyclif ('/home/mpavlov/anaconda/envs/test') and the one you are installing pykaldi on ('/home/mpavlov/anaconda/envs/kaldi'). Normally, I do not think this is a problem. However, the error leads me to believe that there is no python installation in '/home/mpavlov/anaconda/envs/kaldi' since the python-dev (libpython3.5m.so) is missing. 

1. Make sure`which python` returns  '/home/mpavlov/anaconda/envs/kaldi/bin/python'

2. Do `ls /home/mpavlov/anaconda/envs/kaldi/lib | grep python` to see which python libs are there in your environment. Paste the results here.

3. Run the install command in debug mode and copy the complete output here
`DEBUG=1 python setup.py install`

Thanks

**Comment by fgvbrt** [comment]
Hi, when I reported error I worked in `test` environment and it is strange that kaldi environment was used.
Now I deleted `test` and 'kaldi environment` and run installation from scratch.
1. which python gives correct output:
/home/mpavlov/anaconda/envs/kaldi/bin/python
2. ls /home/mpavlov/anaconda/envs/kaldi/lib | grep python
libpython3.6m.a
libpython3.6m.so
libpython3.6m.so.1
libpython3.6m.so.1.0
python3.6
3. install log see attached file 
[install.log](https://github.com/pykaldi/pykaldi/files/1929147/install.log)

**Comment by vrmpx** [comment]
For some reason CMake does not find the correct python libraries (pointing to 3.5 instead of 3.6). Since you mentioned deleting the environments, can you also try and remove CMake cache files (by deleting the build folder in your pykaldi directory)?

**Comment by fgvbrt** [comment]
Hi, when I deleted build directory,  the installation  was successful. Thanks!
