### ISSUE TITLE
DecodableNnetSimpleLoopedInfo not valid for AmNnetSimple model

### ISSUE THREAD

**Issue by 34153320** [pykaldi/pykaldi#37]
My code is:

from kaldi.nnet3 import DecodableNnetSimpleLoopedInfo as from_am
decodable_opts  = NnetSimpleLoopedComputationOptions()
decodable_opts.frames_per_chunk = 20
decodable_opts.extra_left_context_initial = 10
decodable_opts.frame_subsampling_factor  = 1
decodable_opts.acoustic_scale   = 1.0

acoustic_model = AmNnetSimple()
decodable_info  =  from_am(decodable_opts, acoustic_model)

and the error report is:

decodable_info  =  from_am(decodable_opts, acoustic_model)
TypeError: __init__() argument nnet is not valid for ::kaldi::nnet3::Nnet * (_am_nnet_simple.AmNnetSimple instance given): expecting _nnet_nnet.Nnet instance, got _am_nnet_simple.AmNnetSimple instance

in the /nnet3/decodable-simple-looped.clif, it shows 

@add__init__
      def `DecodableNnetSimpleLoopedInfo` as from_am(
          self, opts: NnetSimpleLoopedComputationOptions, nnet: AmNnetSimple)

so AmNnetSimple should work....I dont know where is the problem

**Comment by 34153320** [comment]
Sorry... another problem... When I use OnlineNnet2FeaturePipelineInfo, in the Kaldi source file, it includes  'ivector_extractor_info' as 'OnlineIvectorExtractionInfo'. However, in your wrapper, 

in online2/online-nnet2-feature-pipeline.clif,  OnlineNnet2FeaturePipelineInfo has disabled ivector_extractor_info...

**Comment by dogancan** [comment]
It seem that property was disabled because OnlineIvectorExtractionInfo does not have a copy constructor. This is something CLIF requires. To enable it, we need to change kaldi source code and it looks like we left doing that for later. 

Do you need to access to this property after constructing OnlineNnet2FeaturePipelineInfo ? Because that is what is disabled at the moment. You should still be able to construct an object of type OnlineNnet2FeaturePipelineInfo by passing it a config object of type OnlineNnet2FeaturePipelineConfig. 
I am asking because this is a pretty advanced functionality that is hardly used inside kaldi.

**Comment by 34153320** [comment]
Yeah, I am doing an online demo. So ivector_extractor_info will be used. Thanks. I will try the OnlineNnet2FeaturePipelineConfig. I am try to pass the invector_extractor_info through register.

**Comment by dogancan** [comment]
`OnlineNnetFeaturePipelineInfo` now exposes `ivector_extractor_info` member. Closing this.
