### ISSUE TITLE
Support of latgen-faster-mapped

### ISSUE THREAD

**Issue by dawn1dusk** [pykaldi/pykaldi#48]
Are there any plan for PyKaldi to support latgen-faster-mapped function? It is under bin package.

**Comment by dogancan** [comment]
I guess you are asking if we are planning to add a Python script to PyKaldi that behaves similar to latgen-faster-mapped executable in Kaldi. We don't intend to replicate the behavior of existing Kaldi executables since we don't see the benefit apart from showing how it can be done using PyKaldi. I mean why not use the existing latgen-faster-mapped binary if that is the desired functionality? If you don't mind me asking, what is the use case you have in mind that is not answered by the existing Kaldi binary? 

There is an example [here](https://github.com/pykaldi/pykaldi/blob/master/examples/gmm-decode-faster/gmm-decode-faster.py) which shows how gmm-decode-faster can be implemented using PyKaldi. It should be fairly straightforward to implement something similar for latgen-faster-mapped. I believe all of the wrappers necessary for implementing such a script already exist in PyKaldi.

**Comment by dawn1dusk** [comment]
I hope to fully understand how latgen-faster-mapped works. I wonder if there is any resource to assist me to understand the source code. So the purpose of PyKaldi is to use Kaldi in Python. Am I correct?

**Comment by dogancan** [comment]
> I hope to fully understand how latgen-faster-mapped works. I wonder if there is any resource to assist me to understand the source code.

I don't know of any resource other than kaldi documentation and source code that might help you understand how latgen-faster-mapped works. I am not sure why you need/want to fully understand how it works though. My guess is you want to use this decoder by providing precomputed likelihoods and you probably don't care how Kaldi does decoding. If this is the intended goal, you need to construct a DecodableMatrixScaledMapped object from the matrix of likelihoods (separate for each utterance) and call the decode method of the decoder with that decodable object as the argument. Then you can use the get_best_path method of the decoder to retrieve the highest scoring hypothesis.

> So the purpose of PyKaldi is to use Kaldi in Python. Am I correct?

Yes, you are correct. The purpose is to expose Kaldi C++ library API to Python code. You can call Kaldi functions and construct Kaldi objects in Python. That being said, PyKaldi does not provide scripts that are analogues of Kaldi executables. PyKaldi provides the wrappers for the functions/classes needed for implementing such scripts but not the scripts themselves.

**Comment by dawn1dusk** [comment]
I understand. Thanks for your clarification!
