### ISSUE TITLE
How to decode LDA model ?

### ISSUE THREAD

**Issue by codeforequity-at** [pykaldi/pykaldi#55]
Hello,
Can you please give me a hint how to decode an LDA/MLLR model ?

In the "steps/decode.sh", the following features are used (from WSJ recipe):

```
  lda) feats="ark,s,cs:apply-cmvn $cmvn_opts --utt2spk=ark:$sdata/JOB/utt2spk scp:$sdata/JOB/cmvn.scp scp:$sdata/JOB/feats.scp ark:- | splice-feats $splice_opts ark:- ark:- | transform-feats $srcdir/final.mat ark:- ark:- |";;
```
While I think I found the function for doing the splice, I have no idea how to do the "transform-feats".

```
def make_feat_pipeline(base, opts=DeltaFeaturesOptions()):
    def feat_pipeline(wav):
        feats = base.compute_features(wav.data()[0], wav.samp_freq, 1.0)
        return splice_frames(feats, 4, 4)
    return feat_pipeline
```

Can you please provide some hints where to start ?
Thanks

**Comment by dogancan** [comment]
PyKaldi fully supports Kaldi style read/write specifiers. In your example `feats` is a read specifier (aka rspecifier). The simplest way of extracting features in PyKaldi is to use a table reader similar to how it is done in Kaldi. For instance

```
from kaldi.util.table import SequentialMatrixReader

# define the rspecifier for reading the features
feats = "ark,s,cs:apply-cmvn --utt2spk=ark:data/test/utt2spk scp:data/test/cmvn.scp scp:data/test/feats.scp ark:- | splice-feats ark:- ark:- | transform-feats model/final.mat ark:- ark:- |"

with SequentialMatrixReader(feats) as reader:
    for key, feat in reader:
        output = asr.decode(feats)
```

Note that Kaldi executables `apply-cmvn`, `splice-feats` and `transform-feats` should be on your PATH for the above code to work.

You can also extract the features by defining your feature pipeline in Python -- as you have tried to do -- but that is not needed in most scenarios. Unless you need the additional flexibility provided by defining your feature pipeline in Python, I suggest you use a table reader. Using a table reader is not only easier and but also faster since each stage in the pipeline is executed in parallel by the operating system.

**Comment by codeforequity-at** [comment]
Many thanks for your feedback!

Great project you are working on. While Kaldi is very powerful in training and decoding, buildling applications out of it is a pain in the ass - if there weren't such cool companion projects like your pykaldi!
Keep up the good work!

**Comment by dogancan** [comment]
You're welcome.
