### ISSUE TITLE
subprocess.CalledProcessError: Command '['which', 'pyclif']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by saurabhbidwai** [pykaldi/pykaldi#62]
(base) root@analytics-server:~/speechToText/pykaldi# python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    PYCLIF = check_output(['which', 'pyclif'])
  File "setup.py", line 19, in check_output
    return subprocess.check_output(*args, **kwargs).decode("utf-8").strip()
  File "/root/anaconda3/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/root/anaconda3/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'pyclif']' returned non-zero exit status 1.

**Comment by dogancan** [comment]
I am guessing python3 is not the default python in your current environment but pyclif was installed in your default environment. If that is the case, try “python setup.py install”. If you want to install it under python 3, create a new python 3 environment making sure python points to python3 and install everything there.

**Comment by dogancan** [comment]
Did you try the command without the 3 suffix, i.e. python setup.py install ?

**Comment by saurabhbidwai** [comment]
yes

**Comment by dogancan** [comment]
What do you get when you do “which pyclif” ?

**Comment by saurabhbidwai** [comment]
nothing
![2018-12-041](https://user-images.githubusercontent.com/22415674/49421036-34fd7580-f7b4-11e8-844e-e5cd1da63709.png)

**Comment by dogancan** [comment]
Since pyclif executable is not on your path, it seems like one of the following has happened:
1. Your CLIF installation failed. Check output of install_clif.sh.
2. You installed pyclif package under a different python environment. This might happen if another python environment was active when you ran install_clif.sh.

I suggest you start fresh. Create a new python environment and install everything from scratch making sure you check the output install_clif.sh.

**Comment by dogancan** [comment]
Hey could you resolve this issue? I am not sure if there is anything we can do on our end. I am closing this but feel free to reopen it.
