### ISSUE TITLE
New decodable interface

### ISSUE THREAD

**Issue by PCerles** [pykaldi/pykaldi#63]
Hey, I'm trying to implement a (very simple) decodable interface that just wraps a 2D numpy array of log-likelihoods. However, after I instantiate the lattice decoder object and call 

decoder.decode(loglikeDecodable)

I always get this error:
ValueError: decode() argument decodable is not valid: Value invalidated due to capture by std::unique_ptr.

Any ideas why this might be happening? Tried to find examples but couldn't anywhere. Attached the simple class definition below. 

```
from kaldi.itf._decodable_itf import DecodableInterface
class DecodableLogLike(DecodableInterface):
	def __init__(self, loglikes):
		"""
                 loglikes have shape (b, T, C)
		b: batch size
		T: frame length
		C: alphabet size
		"""
		self.loglikes = loglikes[0,:,:]
		self.T = loglikes.shape[0]
		self.C = loglikes.shape[1]

	def is_last_frame(self, frame):
		"""
		Params:
			frame: int
		"""
		if frame == self.T - 1:
			return True
		else:
			return False

	def log_likelihood(self, frame, index):
		"""
		Params:
			frame: int
			index: int
		"""
		return self.loglikes[frame, index]

	def num_frames_ready(self):
		return self.T

	def num_indices(self):
		return self.C
```

**Comment by dogancan** [comment]
The problem is that methods defined in python are not visible to the C++ `DecodableInterface` object. There is a way of making these methods visible in C++ by decorating `DecodableInterface` methods with `@virtual` inside the [CLIF wrapper](https://github.com/pykaldi/pykaldi/blob/master/kaldi/itf/decodable-itf.clif) but I have no idea whether that works out of the box since we never tried it. It is likely that doing so would allow access to python methods in C++ but would break existing subclasses of `DecodableInterface` in pykaldi.

The good news is that if all you need is a decodable object wrapping a likelihood matrix, you can use the existing [DecodableMatrixScaled](https://pykaldi.github.io/api/kaldi.decoder.html#kaldi.decoder.DecodableMatrixScaled) and [DecodableMatrixScaledMapped](https://pykaldi.github.io/api/kaldi.decoder.html#kaldi.decoder.DecodableMatrixScaledMapped) classes.
```
from kaldi.decoder import DecodableMatrixScaled
from kaldi.matrix import SubMatrix

# loglike: numpy array of size num_frames X num_classes
loglike_decodable = DecodableMatrixScaled(SubMatrix(loglikes), 1.0)
```

**Comment by dogancan** [comment]
I haven't checked recently but at one point we were seeing 5-10% difference for regular (non-lattice) decoding. It all depends on how much time is spent on non-decoding activities since pykaldi decoder objects are just thin wrappers around kaldi decoders.

**Comment by PCerles** [comment]
Would there be any reason for a larger drop in lattice decoding?

**Comment by PCerles** [comment]
Thanks! I actually was just using default LatticeFasterDecoderOptions which has a ridiculously large 2147483647 for default maxactive

**Comment by dogancan** [comment]
Sorry about that! PyKaldi classes typically inherit default values from underlying Kaldi classes and in this case the default values are a bit unfortunate. I guess the idea was to not limit max active states in the default case and control the search speed vs accuracy with the beam parameter.

**Comment by dogancan** [comment]
By the way, I don't know if you noticed the recent additions to the `kaldi.asr` module. There are quite a few recognizer classes with a simple to use API in there. See also the example scripts `pykaldi/examples/*-recognizer.py` which might help you get started with a saner baseline configuration.

**Comment by PCerles** [comment]
Thank you! Will check those out.
