### ISSUE TITLE
How to add kaldi functionality?

### ISSUE THREAD

**Issue by PCerles** [pykaldi/pykaldi#64]
Hi, let's say I wanted to add this function: http://kaldi-asr.org/doc/lattice-to-post_8cc.html
to pykaldi with python bindings. Is there some documentation I could go through to generate the python binding? Thank you!

**Comment by PCerles** [comment]
Never mind, I feel like the best way to approach this is to rewrite the script in python using the lower-level kaldi functions.

**Comment by dogancan** [comment]
I don't think I quite follow. Are you asking if you can wrap the main function inside the executable? You can't do that directly with CLIF. You would have to write a shim C++ function that you can wrap with CLIF. Also, why would you want to do that? Why not just use kaldi executable if that is what you need?

Indeed, the best way to do this is to write the function in python. I mean that is what pykaldi is for :) In this specific case, the Kaldi executable is a simple wrapper around a couple of functions. Most of the code in that main function is for parsing command-line options and file I/O.

In python you would probably want to write a simple function like

```python
from kaldi.fstext.utils import scale_lattice, lattice_scale
from kaldi.lat.functions import top_sort_lattice_if_needed, lattice_forward_backward

def lattice_to_post(lat, lm_scale=1.0, acoustic_scale=1.0):
    scale_lattice(lattice_scale(lm_scale, acoustic_scale), lat)
    top_sort_lattice_if_needed(lat)
    lat_like, post, lat_ac_like = lattice_forward_backward(lat)
```
since you probably don't need to read/write lattices as part of this function.

**Comment by PCerles** [comment]
Got it! Thanks so much for your help, I'm understanding the repo much better now.

**Comment by dogancan** [comment]
You're welcome. If you need to do further processing on the posteriors, you will probably want to construct a [Posterior](https://pykaldi.github.io/api/kaldi.hmm.html?highlight=posterior#kaldi.hmm.Posterior) object and use its methods. This is different from how posteriors are processed in kaldi using free standing functions. Posteriors object returned by `lattice_forward_backward` is of type `List[List[Tuple[int,float]]]`, since CLIF automatically converts `std::vector` to python `List` and `std::tuple` to python `Tuple`. While that is very convenient for processing it in python, it also means that it doesn't share memory with the posteriors object in C++ which is of type `vector<vector<tuple<int,float>>>`, so posteriors have to be marshalled/unmarshalled every time you pass them between python and C++. This is one of the not-so-obvious gotchas which we probably should mention somewhere in the documentation. Luckily, most of the objects returned by kaldi functions, such as matrices, FSTs, models, etc. share memory with C++ so passing them between python and C++ is cheap.

**Comment by PCerles** [comment]
Got it.  Unrelated question, but is pykaldi designed to update with upstream kaldi improvements, e.g. whenever this is merged into master (https://github.com/kaldi-asr/kaldi/pull/2322/files)?

**Comment by dogancan** [comment]
Yes, we very much intend to keep in sync with upstream changes. The way we do it now is to make a big update every now and then since we have limited time to do it. I have been wanting to catch up with upstream for some time now but haven't had the time. I was also kind of waiting for a CLIF update, which might change how we wrap and package things depending what new functionality the update brings, but that hasn't happened for quite some time.

The medium term goal is to upstream the changes we made to kaldi so pykaldi can be built against vanilla kaldi. The long term goal is to integrate pykaldi to kaldi source tree so it can be developed along  with the rest of kaldi. I have talked with Dan Povey and he likes the idea but we haven't acted on these things yet.

**Comment by PCerles** [comment]
Awesome, good to hear. I think vanilla Kaldi is set up very well to share and replicate research, but not an easy integration with acoustic models trained in Torch/Tensorflow/etc. This repo has made that way way easier. Thanks so much for your work on this.

**Comment by dogancan** [comment]
I am glad to hear that! Please do share your code if you can. Unfortunately, real world examples of  how pykaldi can be useful for research as well as application development is still dearly missing from the repo.
