### ISSUE TITLE
conda install fail

### ISSUE THREAD

**Issue by cici20052016** [pykaldi/pykaldi#66]
conda install -c pykaldi pykaldi
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pykaldi

Current channels:

  - https://conda.anaconda.org/pykaldi/osx-64
  - https://conda.anaconda.org/pykaldi/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by dogancan** [comment]
It seems like you are trying to install on OS X. We don't support OS X (yet).

**Comment by cici20052016** [comment]
thanks, when OS X will be supported'?

**Comment by dogancan** [comment]
No ETA. It has low priority for us. I don't expect it to happen any time soon unless there is suddenly strong demand for it or someone else wants to tackle the problem and sends us a pull request.

**Comment by davidavdav** [comment]
Hi, this looks like a great package.  It works straight out of the box in docker, but I have no easy way of developing in docker, so I tried installing locally, and I even installed conda for the purpose (never needed it before--yet another package manager), but then hit this Issue.  

The README.md says the following, which suggests that things should work on MacOS / OS X.  

Installation

If you are using a relatively recent Linux or macOS, such as Ubuntu >= 16.04, CentOS >= 7 or macOS >= 10.13, you should be able to install PyKaldi without too much trouble. Otherwise, you will likely need to tweak the installation scripts.

**Comment by vrmpx** [comment]
Hi @davidavdav,
Unfortunately we do not distribute conda packages for macOS yet. As of right now, the only way to get it for macOS is installing from source.

Let me know if you have any other difficulties with the installation.

**Comment by davidavdav** [comment]
Thx, yes, that is what I figured out, but perhaps the README could be made a little more clear on that point---maybe it is just the way it is structured.
