### ISSUE TITLE
WebRTC server

### ISSUE THREAD

**Issue by danijel3** [pykaldi/pykaldi#76]
This is really a feature-request/suggestion of something I'm in the process of completion. I am going to be realeasing a separate project which allows to talk to the `online2-tcp-nnet3-decode-faster` directly from the browser using WebRTC. Kinda like what you can do with Google Speech in Chrome, but for Kaldi.

Now, I'll do my project anyway (as a demo for people that wish to integrate Kaldi into their projects without using Python), but seeing that my WebRTC server is written in Python, using the excellent aiortc library, I think it would make a lot of sense to integrate it directly with pykaldi.

I'd be glad to do a PR, but I wanted to ask here, how would you prefer to do this? Would you like to see it in an already existing directory (eg. examples) or would you prefer a new one? Or maybe you'd like to have a completely separate repo for that?

Also, do you plan to do online recognition from the microphone using some other Python GUI? Did you consider adding some kind of scripts that would download pre-trained models from the Kaldi website, to show off the project?

**Comment by dogancan** [comment]
Hey @danijel3. This sounds like an awesome project! We would be happy to support it as part of pykaldi or as a separate project, however you see fit!

> I'd be glad to do a PR, but I wanted to ask here, how would you prefer to do this? Would you like to see it in an already existing directory (eg. examples) or would you prefer a new one? Or maybe you'd like to have a completely separate repo for that?

If we are going to add it to pykaldi repository, putting it inside the examples directory would be best. I am guessing your webrtc server will have additional package dependencies. We prefer to put such things inside the examples directory to avoid introducing new dependencies for pykaldi. I think it would make more sense to have this project as a separate repository especially if there is a good amount of code in it. It is your call really. If you would like to have it in a separate repository, we can also put it under pykaldi organization on github, such as https://github.com/pykaldi/webrtc-server.

> Also, do you plan to do online recognition from the microphone using some other Python GUI?

I would like to do this but I have limited amount of time to work on pykaldi so I don't know if I will get to doing this any time soon. If you would like to do something like that, I would be more than happy to help though.

> Did you consider adding some kind of scripts that would download pre-trained models from the Kaldi website, to show off the project?

I did consider this but left it for later due to time constraints. I recently updated the example code we have in the README, which should be more or less drop in for pre-trained aspire chain models. Again, if you would like to work on this, I would be more than happy to help.

**Comment by danijel3** [comment]
Cool. It'd be my pleasure to contribute here. A separate repo is not needed. The extra requirements are not that terrible and storing it in the example dir will be perfect.

I suggest we leave this issue open for now until I make a PR. and then we can link it there.

**Comment by bmilde** [comment]
If you have a project that you would like to get featured on the main README page, then please get in touch!
